# Elasticsearch 内网部署配置
# ======================== Elasticsearch Configuration =========================

# ---------------------------------- Cluster -----------------------------------
cluster.name: es-admin-cluster
node.name: es-admin-node-1

# ----------------------------------- Paths ------------------------------------
path.data: /data/elasticsearch/data
path.logs: /data/elasticsearch/logs

# ---------------------------------- Network -----------------------------------
# 绑定到所有网络接口
network.host: 0.0.0.0
# HTTP端口
http.port: 9200
# 传输端口
transport.tcp.port: 9300

# --------------------------------- Discovery ----------------------------------
# 单节点模式（内网环境）
discovery.type: single-node

# ---------------------------------- Security ----------------------------------
# 启用安全认证
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true

# 如果不需要HTTPS，可以禁用SSL
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# ---------------------------------- Various -----------------------------------
# 防止内存交换
bootstrap.memory_lock: true

# 设置JVM堆内存（建议设置为物理内存的一半，最大不超过32GB）
# 这里设置为4GB，可以根据服务器配置调整
# 在jvm.options文件中设置: -Xms4g -Xmx4g

# ---------------------------------- Index ------------------------------------
# 默认分片数设置
action.auto_create_index: true
# 单节点环境，分片和副本设置
index.number_of_shards: 1
index.number_of_replicas: 0

# ---------------------------------- 文本分析 ----------------------------------
# 使用标准分析器（不需要安装额外插件）
# 如需中文分词，请安装IK分词插件后启用以下配置：
# analysis.analyzer.ik_max_word.type: ik_max_word
# analysis.analyzer.ik_smart.type: ik_smart

# ---------------------------------- 性能优化 ----------------------------------
# 线程池设置
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# 刷新间隔设置（提高写入性能）
index.refresh_interval: 30s

# 批量操作设置
http.max_content_length: 500mb

# ---------------------------------- 监控 ------------------------------------
# 启用集群统计
xpack.monitoring.collection.enabled: true